---
namespace: "{{ enclave }}"
source_secret_name: "{{ base_domain }}-tls"
k8s_api_retry_number_max_limit: 10
k8s_api_retry_delay_sec: 3
model_docker_protocol: https
model_resources_cpu: 256m
max_token_ttl_minutes: 259200  # 60*24*180, 180 days
collector:
  region: "{{ aws_region }}"
model_resources_mem: 256Mi
log_level: debug
monitoring_namespace: kube-monitoring
model_examples_git_url: "git@github.com:legion-platform/legion.git"
model_reference: "origin/develop"