---

- name: Generate JWT Secret
  set_fact:
    enclave_jwt_secret: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
    tmp_values_file: "{{ tmp_dir }}/legion-values.{{ cluster_name }}.yaml"

- name: Create legion configuration (values) file
  template:
    src: legion-values.yaml.j2
    dest: "{{ tmp_values_file }}"
    mode: 0644

# TODO: Remove after resolving of the issue https://github.com/legion-platform/legion/issues/150
- name: Delete Legion Validationg Webhook
  shell: "kubectl --context {{ cluster_name }} delete --ignore-not-found validatingwebhookconfigurations legion-validating-webhook-configuration"

# TODO: Remove after resolving of the issue https://github.com/legion-platform/legion/issues/150
- name: Delete Legion Mutating Webhook
  shell: "kubectl --context {{ cluster_name }} delete --ignore-not-found mutatingwebhookconfigurations legion-mutating-webhook-configuration"

# TODO: Remove after resolving of the issue https://github.com/legion-platform/legion/issues/150
- name: Delete Legion CRDs
  shell: "kubectl --context {{ cluster_name }} delete --ignore-not-found crd {{ item }}.legion.legion-platform.org"
  loop:
    - "modeltrainings"
    - "vcscredentials"
    - "modeldeployments"

- name: Install legion enclave helm chart
  include_role:
    name: deploy_helm_chart
  vars:
    release_name: legion
    values_file: "{{ tmp_values_file }}"
    namespace: "{{ enclave }}"
    src_chart_name: legion
    chart_name: legion-helm/legion
    chart_version: "{{ legion_version }}"